env:
  node: true
  commonjs: true
  es6: true
  jest: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  semi: ["error", "never"]
  indent: ["error", 4]
  comma-dangle: 0
  no-restricted-syntax: 0
  class-methods-use-this: 0
  implicit-arrow-linebreak: 0